---
# No defaults. Define in host_vars/group_vars.
# Example:
# fail2ban_base_bantime: "1h"
# fail2ban_base_findtime: "10m"
# fail2ban_base_maxretry: 5
# fail2ban_base_ignoreip:
#   - "127.0.0.1/8"
#   - "::1"
# fail2ban_base_backend: "systemd"
