"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = """
[╭─](bold blue)$env_var$directory$git_branch$git_status$nodejs$python$docker_context$line_break[╰─](bold blue)$character"""

[package]
disabled = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[directory]
style = "bold cyan"
read_only = " "
truncation_length = 3
format = " [$path]($style)"

[env_var.PROJECT_NAME]
format = " [$env_value]($style)"
style = "bold cyan"

[line_break]
disabled = false

[git_branch]
symbol = ""
style = "bold purple"
format = "[ -> $branch]($style)"

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\] ]($style) )'
disabled = false

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol($version )]($style)"
disabled = true

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol($version )]($style)"
disabled = true

[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style) "
disabled = true
