---
# No defaults. Define in host_vars/group_vars.
# Example:
# backup_restic_repo: /mnt/backup/restic-repo
# backup_restic_src: /srv/docker
# backup_restic_password: "change_me_please"
# backup_restic_retention_days: 7
# backup_restic_retention_weeks: 4
# backup_restic_retention_months: 6
# backup_restic_timer_schedule: "daily"
