---
# No defaults. Define in host_vars/group_vars.
# Example:
# docker_prune_schedule: "weekly"
# docker_prune_command: "/usr/bin/docker system prune --all --force"
# docker_prune_service_name: "docker-prune"
