---
# No defaults. Define in host_vars/group_vars.
# Example:
# common_tools_packages:
#   - curl
#   - git
#   - nano
#   - tmux
#   - htop
#   - rsync
#   - unzip
#   - jq
#   - dnsutils
#   - iotop
#   - iftop
#   - nload
#   - net-tools
#   - vnstat
#   - needrestart
#   - ncdu
#   - tcpdump
#   - lsof
#   - strace
