---
- name: Prepare Raspberry Pi base OS
  hosts: raspberry_pi_boxes
  become: true
  gather_facts: true
  roles:
    - pi_base
    - unattended_upgrades
    - fail2ban_base
    - time_sync
    - log_hygiene
    - node_exporter
    - storage_layout
    - docker_engine
    - docker_prune
    - common_tools
    - tmux_config
    - daily_report
    - backup_restic
    - docker_smoke_test
