---
- name: Import base playbook
  import_playbook: pi-base.yml

- name: Import services playbook
  import_playbook: pi-services.yml

- name: Import smoke tests playbook
  import_playbook: pi-smoke.yml
