---
- name: Create systemd service unit
  ansible.builtin.template:
    src: docker-prune.service.j2
    dest: "/etc/systemd/system/{{ docker_prune_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Create systemd timer unit
  ansible.builtin.template:
    src: docker-prune.timer.j2
    dest: "/etc/systemd/system/{{ docker_prune_service_name }}.timer"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable and start prune timer
  ansible.builtin.systemd:
    name: "{{ docker_prune_service_name }}.timer"
    enabled: true
    state: started
