---
- name: Install node exporter package
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
  tags: [node_exporter]

- name: Configure node exporter listen address
  ansible.builtin.template:
    src: node_exporter.default.j2
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: "0644"
  notify: Restart node_exporter
  tags: [node_exporter]

- name: Ensure node exporter service is enabled and running
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
  tags: [node_exporter]
